# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-15 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shows',
            old_name='first_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='last_name',
        ),
    ]
