# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-17 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_app', '0002_auto_20190215_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='description',
            field=models.TextField(default='something about tv show'),
            preserve_default=False,
        ),
    ]
