# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-19 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_app', '0004_auto_20190219_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
